### ISSUE TITLE
can not use use_frameworks!

### ISSUE THREAD

**Issue by sunzongzheng** [react-native-tvos/react-native-tvos#575]
### Description

When I don't use use_frameworks everything works fine, when I use use_frameworks I get an error

### React Native Version

0.72.4-0

### Output of `npx react-native info`

```shell
System:
  OS: macOS 13.5
  CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Memory: 1.81 GB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.20.2
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 8.19.4
    path: /usr/local/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    API Levels:
      - "16"
      - "25"
      - "26"
      - "30"
      - "33"
      - "34"
    Build Tools:
      - 30.0.2
      - 30.0.3
      - 34.0.0
    System Images:
      - android-25 | Android TV Intel x86 Atom
      - android-25 | Google Play Intel x86 Atom
      - android-26 | Google Play Intel x86 Atom
      - android-30 | Google Play Intel x86 Atom
      - android-34 | Google APIs Intel x86_64 Atom
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10406996
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 1.8.0_382
    path: /Users/sunzongzheng/Library/Java/JavaVirtualMachines/corretto-1.8.0_382/Contents/Home/bin/javac
  Ruby:
    version: 3.2.1
    path: /Users/sunzongzheng/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native: Not Found
  react-native-macos: Not Found
  react-native-tvos:
    installed: 0.72.4-0
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

1. `react-native init TestApp12 --template=react-native-tvos@latest`
2. `cd TestApp12`
3. `rm -rf node_modules ios/Pods && yarn && USE_FRAMEWORKS=static npx pod-install && yarn ios`
4. Everything works fine now, then repeat`rm -rf node_modules ios/Pods && yarn && USE_FRAMEWORKS=static npx pod-install && yarn ios`

Then I got an error
```shell
  (node_modules/react-native/ReactCommon/cxxreact/Instance.cpp:24:10)

  22 | #include <folly/MoveWrapper.h>
  23 | #include <folly/json.h>
> 24 | #include <react/debug/react_native_assert.h>
     |          ^ 'react/debug/react_native_assert.h' file not found
  25 |
  26 | #include <glog/logging.h>
  27 |
```

After searching, I added the following code to Podfile to solve this problem
```shell
def append_header_search_path(target, path)
      target.build_configurations.each do |config|
          # Note that there's a space character after `$(inherited)`.
          config.build_settings["HEADER_SEARCH_PATHS"] ||= "$(inherited) "
          config.build_settings["HEADER_SEARCH_PATHS"] << path
      end
end

post_install do |installer|
  config = use_native_modules!
  # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
  react_native_post_install(
    installer,
    config[:reactNativePath],
    :mac_catalyst_enabled => false
  )
  __apply_Xcode_12_5_M1_post_install_workaround(installer)

  installer.pods_project.targets.each do |target|
    if ["React-cxxreact-framework", "React-utils-framework", "React-utils-iOS", "React-cxxreact-iOS"].any? { |t| t == target.name }
      append_header_search_path(target, "${PODS_ROOT}/../../node_modules/react-native/ReactCommon")
    end
  end
end
```

And repeat`rm -rf node_modules ios/Pods && yarn && USE_FRAMEWORKS=static npx pod-install && yarn ios`
Then I got an error
```shell
❌  (node_modules/react-native/ReactCommon/react/nativemodule/core/platform/ios/ReactCommon/RCTTurboModuleManager.h:15:9)

  13 | #import <React/RCTTurboModuleRegistry.h>
  14 | #import <ReactCommon/RuntimeExecutor.h>
> 15 | #import <ReactCommon/TurboModuleBinding.h>
     |         ^ 'ReactCommon/TurboModuleBinding.h' file not found
  16 | #import "RCTTurboModule.h"
  17 |
  18 | RCT_EXTERN void RCTTurboModuleSetBindingMode(facebook::react::TurboModuleBindingMode bindingMode);
```

I found an [issue](https://github.com/facebook/react-native/issues/38067) with the same problem, but the problem is still unresolved

### Snack, code example, screenshot, or link to a repository

https://github.com/sunzongzheng/react-native-tvos-demo

**Comment by douglowder** [comment]
@sunzongzheng is this issue addressed in version 0.72.6-0?

**Comment by sunzongzheng** [comment]
> npx react-native info

@douglowder The problem still exists. I recently upgraded xcode and system versions. Below is my latest environment information.

```text
System:
  OS: macOS 13.6
  CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Memory: 5.01 GB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.20.2
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 8.19.4
    path: /usr/local/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK:
    API Levels:
      - "16"
      - "25"
      - "26"
      - "30"
      - "33"
      - "34"
    Build Tools:
      - 30.0.2
      - 30.0.3
      - 34.0.0
    System Images:
      - android-25 | Android TV Intel x86 Atom
      - android-25 | Google Play Intel x86 Atom
      - android-26 | Google Play Intel x86 Atom
      - android-30 | Google Play Intel x86 Atom
      - android-34 | Google APIs Intel x86_64 Atom
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10406996
  Xcode:
    version: 15.0/15A240d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 1.8.0_382
    path: /Users/sunzongzheng/Library/Java/JavaVirtualMachines/corretto-1.8.0_382/Contents/Home/bin/javac
  Ruby:
    version: 3.2.1
    path: /Users/sunzongzheng/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native: Not Found
  react-native-macos: Not Found
  react-native-tvos:
    installed: 0.72.6-0
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

**Comment by douglowder** [comment]
Just to be clear, this is a problem with the RN core distribution that this repo is based on. It is being worked on by Meta under issue https://github.com/facebook/react-native/issues/38283 . Once they have a fix we will merge it here.

**Comment by douglowder** [comment]
@sunzongzheng I was able to get `use_frameworks` working in the latest release (0.73.1-3).

You will need to make sure that only one target exists in your Podfile -- if you have both iOS and tvOS targets, this will fail.

If your project includes React Navigation, you will also need the following added to your Podfile:

```ruby
  pre_install do |installer|
    installer.pod_targets.each do |pod|
      if pod.name.start_with?('RNScreens') || pod.name.start_with?('RNReanimated')
        def pod.build_type;
          Pod::BuildType.static_library
        end
      end
    end
  end
```

Closing this for now -- if you see any issues after applying the above, add a comment here and I can reopen this.

**Comment by Flawlessdawdwa** [comment]
post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    installer.pods_project.targets.each do |target|
    if target.name == "React-Core-AccessibilityResources"
      target.remove_from_project
      end
    end
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
  this is what my Podfile's last code looks like, im getting the error : 
  'react/debug/react_native_assert.h' file not found
  i tried many things but nothing works.. can you help? @douglowder
